CREATE TABLE IF NOT EXISTS silver_srbp_sales_ds.fund_cash
(
  FUND_CASH_ACCT_SEQ INT64,
  INVST_PLAN_ARR_SEQ INT64,
  ACCT_CASH_FUND STRING,
  ACCT_CASH_FUND_TYPE_CDE STRING,
  CCY_ACCT_CASH_FUND_CDE STRING,
  LAST_INGESTION_TIMESTAMP TIMESTAMP,
  PRM_LNE_OF_BUS_CDE_FILTER STRING,
  CTRY_CDE_FILTER STRING,
  ENTITY_CDE_FILTER STRING
)
PARTITION BY DATE(LAST_INGESTION_TIMESTAMP)
CLUSTER BY CTRY_CDE_FILTER, ENTITY_CDE_FILTER;


MERGE silver_srbp_sales_ds.fund_cash T
USING (
  SELECT
    SAFE_CAST(FUND_CASH_ACCT_SEQ AS INT64) AS FUND_CASH_ACCT_SEQ,
    SAFE_CAST(INVST_PLAN_ARR_SEQ AS INT64) AS INVST_PLAN_ARR_SEQ,
    ACCT_CASH_FUND,
    ACCT_CASH_FUND_TYPE_CDE,
    CCY_ACCT_CASH_FUND_CDE,
    safe.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP) AS LAST_INGESTION_TIMESTAMP,
    PRM_LNE_OF_BUS_CDE_FILTER,
    CTRY_CDE_FILTER,
    ENTITY_CDE_FILTER
  FROM raw_srbp_sales_ds.FUND_CASH
) S
ON T.FUND_CASH_ACCT_SEQ = S.FUND_CASH_ACCT_SEQ

WHEN MATCHED THEN
  UPDATE SET
    T.INVST_PLAN_ARR_SEQ = S.INVST_PLAN_ARR_SEQ,
    T.ACCT_CASH_FUND = S.ACCT_CASH_FUND,
    T.ACCT_CASH_FUND_TYPE_CDE = S.ACCT_CASH_FUND_TYPE_CDE,
    T.CCY_ACCT_CASH_FUND_CDE = S.CCY_ACCT_CASH_FUND_CDE,
    T.LAST_INGESTION_TIMESTAMP = S.LAST_INGESTION_TIMESTAMP,
    T.PRM_LNE_OF_BUS_CDE_FILTER = S.PRM_LNE_OF_BUS_CDE_FILTER,
    T.CTRY_CDE_FILTER = S.CTRY_CDE_FILTER,
    T.ENTITY_CDE_FILTER = S.ENTITY_CDE_FILTER

WHEN NOT MATCHED THEN
  INSERT (
    FUND_CASH_ACCT_SEQ,
    INVST_PLAN_ARR_SEQ,
    ACCT_CASH_FUND,
    ACCT_CASH_FUND_TYPE_CDE,
    CCY_ACCT_CASH_FUND_CDE,
    LAST_INGESTION_TIMESTAMP,
    PRM_LNE_OF_BUS_CDE_FILTER,
    CTRY_CDE_FILTER,
    ENTITY_CDE_FILTER
  )
  VALUES (
    S.FUND_CASH_ACCT_SEQ,
    S.INVST_PLAN_ARR_SEQ,
    S.ACCT_CASH_FUND,
    S.ACCT_CASH_FUND_TYPE_CDE,
    S.CCY_ACCT_CASH_FUND_CDE,
    S.LAST_INGESTION_TIMESTAMP,
    S.PRM_LNE_OF_BUS_CDE_FILTER,
    S.CTRY_CDE_FILTER,
    S.ENTITY_CDE_FILTER
  );