CREATE OR REPLACE TABLE silver_srbp_sales_ds.UNINVESTMENT
(
  ACCT_EXTNL_NUM STRING,
  SYS_EXTNL_CDE STRING,
  CTRY_INVST_ACCT_CDE STRING,
  GRP_MEMBR_INVST_ACCT_CDE STRING,
  SRCE_SYS_NAME STRING,
  ACCT_MIG_FUND_IND STRING,
  LAST_INGESTION_TIMESTAMP TIMESTAMP,
  PRM_LNE_OF_BUS_CDE_FILTER STRING,
  CTRY_CDE_FILTER STRING,
  ENTITY_CDE_FILTER STRING
)
PARTITION BY DATE(LAST_INGESTION_TIMESTAMP)
CLUSTER BY CTRY_CDE_FILTER, ENTITY_CDE_FILTER;

  MERGE silver_srbp_sales_ds.UNINVESTMENT T
  USING (
    SELECT
      ACCT_EXTNL_NUM,
      SYS_EXTNL_CDE,
      CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE,
      SRCE_SYS_NAME,
      ACCT_MIG_FUND_IND,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP) AS LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    FROM raw_srbp_sales_ds.UNINVESTMENT

    -- 🔥 Incremental load
    WHERE SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP)
          >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)

  ) S

  -- 🔑 Composite Key (important)
  ON T.ACCT_EXTNL_NUM = S.ACCT_EXTNL_NUM
  AND T.SYS_EXTNL_CDE = S.SYS_EXTNL_CDE

  WHEN MATCHED THEN
    UPDATE SET
      CTRY_INVST_ACCT_CDE = S.CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE = S.GRP_MEMBR_INVST_ACCT_CDE,
      SRCE_SYS_NAME = S.SRCE_SYS_NAME,
      ACCT_MIG_FUND_IND = S.ACCT_MIG_FUND_IND,
      LAST_INGESTION_TIMESTAMP = S.LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER = S.PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER = S.CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER = S.ENTITY_CDE_FILTER

  WHEN NOT MATCHED THEN
    INSERT (
      ACCT_EXTNL_NUM,
      SYS_EXTNL_CDE,
      CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE,
      SRCE_SYS_NAME,
      ACCT_MIG_FUND_IND,
      LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    )
    VALUES (
      S.ACCT_EXTNL_NUM,
      S.SYS_EXTNL_CDE,
      S.CTRY_INVST_ACCT_CDE,
      S.GRP_MEMBR_INVST_ACCT_CDE,
      S.SRCE_SYS_NAME,
      S.ACCT_MIG_FUND_IND,
      S.LAST_INGESTION_TIMESTAMP,
      S.PRM_LNE_OF_BUS_CDE_FILTER,
      S.CTRY_CDE_FILTER,
      S.ENTITY_CDE_FILTER
    );

