CREATE OR REPLACE TABLE silver_srbp_sales_ds.INVESTMENT_DATA
(
  INVST_PLAN_ARR_SEQ_NUM INT64,
  SEQ_DISP_NUM STRING,
  CTRY_INVST_ACCT_CDE STRING,
  GRP_MEMBR_INVST_ACCT_CDE STRING,
  ACCT_INVST_NUM STRING,
  ENGMT_STYLE_CDE STRING,
  INVST_PLAN_NUM STRING,
  INVST_PLAN_STAT_CDE STRING,
  PDCY_INVST_CDE STRING,
  PLAN_INSTR_NEXT_TM TIMESTAMP,
  PLAN_INSTR_NEXT_DT DATE,
  CCY_INVST_REG_CDE STRING,
  INVST_REG_AMT NUMERIC,
  CCY_INVST_ACCUM_CDE STRING,
  INVST_ACCUM_AMT NUMERIC,
  CNTRB_SUCS_TTL_CNT INT64,
  CNTRB_LAST_DT_TM TIMESTAMP,
  MDUN_SYS_CDE STRING,
  LAST_INGESTION_TIMESTAMP TIMESTAMP,
  PRM_LNE_OF_BUS_CDE_FILTER STRING,
  CTRY_CDE_FILTER STRING,
  ENTITY_CDE_FILTER STRING
)
PARTITION BY DATE(LAST_INGESTION_TIMESTAMP)
CLUSTER BY CTRY_CDE_FILTER, ENTITY_CDE_FILTER;

MERGE silver_srbp_sales_ds.INVESTMENT_DATA T
  USING (
    SELECT
      SAFE_CAST(INVST_PLAN_ARR_SEQ_NUM AS INT64) AS            INVST_PLAN_ARR_SEQ_NUM,
      SEQ_DISP_NUM,
      CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE,
      ACCT_INVST_NUM,
      ENGMT_STYLE_CDE,
      INVST_PLAN_NUM,
      INVST_PLAN_STAT_CDE,
      PDCY_INVST_CDE,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', PLAN_INSTR_NEXT_TM) AS PLAN_INSTR_NEXT_TM,
      SAFE_CAST(PLAN_INSTR_NEXT_DT AS DATE) AS PLAN_INSTR_NEXT_DT,
      CCY_INVST_REG_CDE,
      SAFE_CAST(INVST_REG_AMT AS NUMERIC) AS INVST_REG_AMT,
      CCY_INVST_ACCUM_CDE,
      SAFE_CAST(INVST_ACCUM_AMT AS NUMERIC) AS INVST_ACCUM_AMT,
      SAFE_CAST(CNTRB_SUCS_TTL_CNT AS INT64) AS CNTRB_SUCS_TTL_CNT,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', CNTRB_LAST_DT_TM) AS CNTRB_LAST_DT_TM,
      MDUN_SYS_CDE,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP) AS LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    FROM raw_srbp_sales_ds.INVESTMENT_DATA

    -- 🔥 Incremental load (important)
    WHERE SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP)
          >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)

  ) S

  -- 🔑 Composite Key (recommended)
  ON T.INVST_PLAN_ARR_SEQ_NUM = S.INVST_PLAN_ARR_SEQ_NUM
  AND T.ACCT_INVST_NUM = S.ACCT_INVST_NUM

  WHEN MATCHED THEN
    UPDATE SET
      SEQ_DISP_NUM = S.SEQ_DISP_NUM,
      CTRY_INVST_ACCT_CDE = S.CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE = S.GRP_MEMBR_INVST_ACCT_CDE,
      ENGMT_STYLE_CDE = S.ENGMT_STYLE_CDE,
      INVST_PLAN_NUM = S.INVST_PLAN_NUM,
      INVST_PLAN_STAT_CDE = S.INVST_PLAN_STAT_CDE,
      PDCY_INVST_CDE = S.PDCY_INVST_CDE,
      PLAN_INSTR_NEXT_TM = S.PLAN_INSTR_NEXT_TM,
      PLAN_INSTR_NEXT_DT = S.PLAN_INSTR_NEXT_DT,
      CCY_INVST_REG_CDE = S.CCY_INVST_REG_CDE,
      INVST_REG_AMT = S.INVST_REG_AMT,
      CCY_INVST_ACCUM_CDE = S.CCY_INVST_ACCUM_CDE,
      INVST_ACCUM_AMT = S.INVST_ACCUM_AMT,
      CNTRB_SUCS_TTL_CNT = S.CNTRB_SUCS_TTL_CNT,
      CNTRB_LAST_DT_TM = S.CNTRB_LAST_DT_TM,
      MDUN_SYS_CDE = S.MDUN_SYS_CDE,
      LAST_INGESTION_TIMESTAMP = S.LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER = S.PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER = S.CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER = S.ENTITY_CDE_FILTER

  WHEN NOT MATCHED THEN
    INSERT (
      INVST_PLAN_ARR_SEQ_NUM,
      SEQ_DISP_NUM,
      CTRY_INVST_ACCT_CDE,
      GRP_MEMBR_INVST_ACCT_CDE,
      ACCT_INVST_NUM,
      ENGMT_STYLE_CDE,
      INVST_PLAN_NUM,
      INVST_PLAN_STAT_CDE,
      PDCY_INVST_CDE,
      PLAN_INSTR_NEXT_TM,
      PLAN_INSTR_NEXT_DT,
      CCY_INVST_REG_CDE,
      INVST_REG_AMT,
      CCY_INVST_ACCUM_CDE,
      INVST_ACCUM_AMT,
      CNTRB_SUCS_TTL_CNT,
      CNTRB_LAST_DT_TM,
      MDUN_SYS_CDE,
      LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    )
    VALUES (
      S.INVST_PLAN_ARR_SEQ_NUM,
      S.SEQ_DISP_NUM,
      S.CTRY_INVST_ACCT_CDE,
      S.GRP_MEMBR_INVST_ACCT_CDE,
      S.ACCT_INVST_NUM,
      S.ENGMT_STYLE_CDE,
      S.INVST_PLAN_NUM,
      S.INVST_PLAN_STAT_CDE,
      S.PDCY_INVST_CDE,
      S.PLAN_INSTR_NEXT_TM,
      S.PLAN_INSTR_NEXT_DT,
      S.CCY_INVST_REG_CDE,
      S.INVST_REG_AMT,
      S.CCY_INVST_ACCUM_CDE,
      S.INVST_ACCUM_AMT,
      S.CNTRB_SUCS_TTL_CNT,
      S.CNTRB_LAST_DT_TM,
      S.MDUN_SYS_CDE,
      S.LAST_INGESTION_TIMESTAMP,
      S.PRM_LNE_OF_BUS_CDE_FILTER,
      S.CTRY_CDE_FILTER,
      S.ENTITY_CDE_FILTER
    );