CREATE OR REPLACE TABLE silver_srbp_sales_ds.GHSS_ACCT
(
  ACCT_INVST_NUM STRING,
  GRP_MEMBER_CDE STRING,
  CTRY_CDE STRING,
  CE_INCM_CASH_ACCT_TYPE STRING,
  CE_INCM_CASH_ACCT_CCY_CDE STRING,
  CE_INCM_CASH_ACCT STRING,
  LAST_INGESTION_TIMESTAMP TIMESTAMP,
  PRM_LNE_OF_BUS_CDE_FILTER STRING,
  CTRY_CDE_FILTER STRING,
  ENTITY_CDE_FILTER STRING
)
PARTITION BY DATE(LAST_INGESTION_TIMESTAMP)
CLUSTER BY CTRY_CDE_FILTER, ENTITY_CDE_FILTER;

  MERGE silver_srbp_sales_ds.GHSS_ACCT as  T
  USING (
    SELECT
      ACCT_INVST_NUM,
      GRP_MEMBER_CDE,
      CTRY_CDE,
      CE_INCM_CASH_ACCT_TYPE,
      CE_INCM_CASH_ACCT_CCY_CDE,
      CE_INCM_CASH_ACCT,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP) AS LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    FROM raw_srbp_sales_ds.GHSS_ACCT

    -- 🔥 Incremental load (optional)
    WHERE SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP)
          >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)

  ) S

  -- 🔑 Primary Key (adjust if needed)
  ON T.ACCT_INVST_NUM = S.ACCT_INVST_NUM
  AND T.GRP_MEMBER_CDE = S.GRP_MEMBER_CDE

  WHEN MATCHED THEN
    UPDATE SET
      CTRY_CDE = S.CTRY_CDE,
      CE_INCM_CASH_ACCT_TYPE = S.CE_INCM_CASH_ACCT_TYPE,
      CE_INCM_CASH_ACCT_CCY_CDE = S.CE_INCM_CASH_ACCT_CCY_CDE,
      CE_INCM_CASH_ACCT = S.CE_INCM_CASH_ACCT,
      LAST_INGESTION_TIMESTAMP = S.LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER = S.PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER = S.CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER = S.ENTITY_CDE_FILTER

  WHEN NOT MATCHED THEN
    INSERT (
      ACCT_INVST_NUM,
      GRP_MEMBER_CDE,
      CTRY_CDE,
      CE_INCM_CASH_ACCT_TYPE,
      CE_INCM_CASH_ACCT_CCY_CDE,
      CE_INCM_CASH_ACCT,
      LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    )
    VALUES (
      S.ACCT_INVST_NUM,
      S.GRP_MEMBER_CDE,
      S.CTRY_CDE,
      S.CE_INCM_CASH_ACCT_TYPE,
      S.CE_INCM_CASH_ACCT_CCY_CDE,
      S.CE_INCM_CASH_ACCT,
      S.LAST_INGESTION_TIMESTAMP,
      S.PRM_LNE_OF_BUS_CDE_FILTER,
      S.CTRY_CDE_FILTER,
      S.ENTITY_CDE_FILTER
    ); 
  