CREATE OR REPLACE TABLE silver_srbp_sales_ds.INVST_PLAN
(
  INVS_PLN_ARR_PRD_SEQ_NUM INT64,
  INVST_PLAN_ARR_SEQ_NUM INT64,
  PROD_ALT_NUM STRING,
  PROD_CDE_ALT_CLASS_CDE STRING,
  CTRY_PROD_TRADE_CDE STRING,
  ASET_CLASS_CDE STRING,
  LAST_INGESTION_TIMESTAMP TIMESTAMP,
  PRM_LNE_OF_BUS_CDE_FILTER STRING,
  CTRY_CDE_FILTER STRING,
  ENTITY_CDE_FILTER STRING
)
PARTITION BY DATE(LAST_INGESTION_TIMESTAMP)
CLUSTER BY CTRY_CDE_FILTER, ENTITY_CDE_FILTER;



  MERGE silver_srbp_sales_ds.INVST_PLAN T
  USING (
    SELECT
      SAFE_CAST(INVS_PLN_ARR_PRD_SEQ_NUM AS INT64) AS INVS_PLN_ARR_PRD_SEQ_NUM,
      SAFE_CAST(INVST_PLAN_ARR_SEQ_NUM AS INT64) AS INVST_PLAN_ARR_SEQ_NUM,
      PROD_ALT_NUM,
      PROD_CDE_ALT_CLASS_CDE,
      CTRY_PROD_TRADE_CDE,
      ASET_CLASS_CDE,
      SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP) AS LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    FROM raw_srbp_sales_ds.INVST_PLAN

    -- 🔥 Incremental load (recommended)
    WHERE SAFE.PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S', LAST_INGESTION_TIMESTAMP)
          >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)

  ) S

  -- 🔑 Composite Key (important)
  ON T.INVS_PLN_ARR_PRD_SEQ_NUM = S.INVS_PLN_ARR_PRD_SEQ_NUM
  AND T.INVST_PLAN_ARR_SEQ_NUM = S.INVST_PLAN_ARR_SEQ_NUM

  WHEN MATCHED THEN
    UPDATE SET
      PROD_ALT_NUM = S.PROD_ALT_NUM,
      PROD_CDE_ALT_CLASS_CDE = S.PROD_CDE_ALT_CLASS_CDE,
      CTRY_PROD_TRADE_CDE = S.CTRY_PROD_TRADE_CDE,
      ASET_CLASS_CDE = S.ASET_CLASS_CDE,
      LAST_INGESTION_TIMESTAMP = S.LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER = S.PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER = S.CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER = S.ENTITY_CDE_FILTER

  WHEN NOT MATCHED THEN
    INSERT (
      INVS_PLN_ARR_PRD_SEQ_NUM,
      INVST_PLAN_ARR_SEQ_NUM,
      PROD_ALT_NUM,
      PROD_CDE_ALT_CLASS_CDE,
      CTRY_PROD_TRADE_CDE,
      ASET_CLASS_CDE,
      LAST_INGESTION_TIMESTAMP,
      PRM_LNE_OF_BUS_CDE_FILTER,
      CTRY_CDE_FILTER,
      ENTITY_CDE_FILTER
    )
    VALUES (
      S.INVS_PLN_ARR_PRD_SEQ_NUM,
      S.INVST_PLAN_ARR_SEQ_NUM,
      S.PROD_ALT_NUM,
      S.PROD_CDE_ALT_CLASS_CDE,
      S.CTRY_PROD_TRADE_CDE,
      S.ASET_CLASS_CDE,
      S.LAST_INGESTION_TIMESTAMP,
      S.PRM_LNE_OF_BUS_CDE_FILTER,
      S.CTRY_CDE_FILTER,
      S.ENTITY_CDE_FILTER
    );

